package com.pluralsight.dynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Setter
@Getter
//@Builder
@DynamoDBTable(tableName = "Item")
@ToString
public class Item {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String id;

    @DynamoDBAttribute(attributeName = "name")
    String name;

    @DynamoDBAttribute
    String description;

    @DynamoDBVersionAttribute
    private Long version;
}
